#!/usr/bin/env bash
#read -p "Add comments now " comments;
git status;
git add -A;
read -p "Add comments now " comments;

git commit -m "$comments";
git push;
echo "........";
echo ".......";
git status;
