
insert into video_games(`name`,small_image,large_image,console_id)values('The Addams Family',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Bass Masters Classic Pro Edition',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Bill Walsh College Football',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Boxing Legends of the Ring',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Bust-a-Move',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('ClayFighter',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('College Slam',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Donkey Kong Country',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Earthworm Jim',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Earthworm Jim 2',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Final Fight',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Final Fight 2',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Final Fight 3',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Frank Thomas Big Hurt Baseball',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('John Madden Football',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('John Madden Football 93',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Killer Instinct',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('The Legend of Zelda A Link to the Past',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('The Lost Vikings',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Madden NFL 94',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Madden NFL 95',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Madden NFL 96',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Natsume Championship Wrestling',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('NBA Hangtime',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('NBA Jam',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('NBA Live 95',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('NFL Quarterback Club 96',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Nolan Ryans Baseball',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Shaq Fu',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Star Fox',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Super Mario Kart',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Super Mario World',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Super Off Road',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Super Punch-Out!!',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Tecmo Super Baseball',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Tecmo Super Bowl II Special Edition',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Tecmo Super Bowl III: Final Edition',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Tecmo Super NBA Basketball',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('Troy Aikman NFL Football',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('WWF Raw',NULL,NULL,2);
insert into video_games(`name`,small_image,large_image,console_id)values('WWF Royal Rumble',NULL,NULL,2);
